pull_request_rules:
  - name: ci testing kalo sukses ke squash dengan label
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      comment:
        message: terima kasih atas kontribusinya @{{author}}!
      label:
        add:
            - sudah direview!
      merge:
        method: squash
